# Generated by Django 4.2.7 on 2023-11-26 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pleasanthabit',
            name='related_habit',
        ),
        migrations.RemoveField(
            model_name='usefulhabit',
            name='time_required',
        ),
        migrations.AddField(
            model_name='habit',
            name='is_public',
            field=models.BooleanField(default='False', verbose_name='Публичная ли запись'),
        ),
        migrations.AddField(
            model_name='habit',
            name='time_required',
            field=models.PositiveIntegerField(default=60, verbose_name='Время на выполнение, с'),
        ),
        migrations.AddField(
            model_name='usefulhabit',
            name='related_habit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habit.pleasanthabit', verbose_name='Связанная привычка'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='period',
            field=models.CharField(choices=[('Daily', 'Ежедневно'), ('Weekly', 'Еженедельно')], default='Daily', max_length=10, verbose_name='Периодичность'),
        ),
        migrations.AlterField(
            model_name='usefulhabit',
            name='reward',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Вознаграждение'),
        ),
    ]
